#!/bin/bash
# PC2 Node Installer
# 
# Quick Install:
#   curl -fsSL https://ela.city/install.sh | bash
#
# Or with username:
#   curl -fsSL https://ela.city/install.sh | bash -s -- yourname
#
# Version: 1.0.0

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
PC2_VERSION="${PC2_VERSION:-latest}"
PC2_IMAGE="ghcr.io/elacity/pc2-node:${PC2_VERSION}"
PC2_PORT="${PC2_PORT:-4200}"
INSTALL_DIR="${HOME}/pc2"

echo -e "${BLUE}"
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                    PC2 Node Installer                          ║"
echo "║           Personal Cloud Computer for Elastos                  ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo -e "${NC}"

# Check for Docker
check_docker() {
    if ! command -v docker &> /dev/null; then
        echo -e "${RED}Error: Docker is not installed.${NC}"
        echo ""
        echo "Please install Docker first:"
        echo "  curl -fsSL https://get.docker.com | bash"
        echo ""
        exit 1
    fi
    
    if ! docker info &> /dev/null; then
        echo -e "${RED}Error: Docker is not running or you don't have permission.${NC}"
        echo ""
        echo "Try running: sudo usermod -aG docker \$USER"
        echo "Then log out and log back in."
        echo ""
        exit 1
    fi
    
    echo -e "${GREEN}✓ Docker is installed and running${NC}"
}

# Get username
get_username() {
    if [ -n "$1" ]; then
        PC2_USERNAME="$1"
    elif [ -n "$PC2_USERNAME" ]; then
        # Already set via environment
        :
    else
        echo ""
        echo -e "${YELLOW}Choose your username for yourname.ela.city${NC}"
        echo "  - 3-20 characters"
        echo "  - Letters, numbers, and hyphens only"
        echo "  - Must start with a letter"
        echo ""
        read -p "Username: " PC2_USERNAME
    fi
    
    # Validate username
    if ! [[ "$PC2_USERNAME" =~ ^[a-z][a-z0-9-]{2,19}$ ]]; then
        echo -e "${RED}Invalid username: $PC2_USERNAME${NC}"
        echo "Username must be 3-20 lowercase letters, numbers, or hyphens, starting with a letter."
        exit 1
    fi
    
    echo -e "${GREEN}✓ Username: ${PC2_USERNAME}${NC}"
}

# Check if username is available
check_username_available() {
    echo "Checking if ${PC2_USERNAME} is available..."
    
    GATEWAY_URL="${BOSON_GATEWAY_URL:-https://demo.ela.city}"
    
    RESPONSE=$(curl -s "${GATEWAY_URL}/api/lookup/${PC2_USERNAME}" || echo '{"error": "connection_failed"}')
    
    if echo "$RESPONSE" | grep -q '"error"'; then
        echo -e "${GREEN}✓ Username ${PC2_USERNAME} is available!${NC}"
    else
        echo -e "${RED}Username ${PC2_USERNAME} is already taken.${NC}"
        echo "Please choose a different username."
        exit 1
    fi
}

# Create installation directory
create_install_dir() {
    mkdir -p "$INSTALL_DIR"
    echo -e "${GREEN}✓ Created directory: ${INSTALL_DIR}${NC}"
}

# Create docker-compose.yml
create_compose_file() {
    cat > "$INSTALL_DIR/docker-compose.yml" << EOF
# PC2 Node - Generated by installer
# Your node: https://${PC2_USERNAME}.ela.city

services:
  pc2-node:
    image: ${PC2_IMAGE}
    container_name: pc2-node
    restart: unless-stopped
    ports:
      - "${PC2_PORT}:4200"
    environment:
      - NODE_ENV=production
      - PC2_USERNAME=${PC2_USERNAME}
      - BOSON_GATEWAY_URL=${BOSON_GATEWAY_URL:-https://demo.ela.city}
      - BOSON_PUBLIC_DOMAIN=${BOSON_PUBLIC_DOMAIN:-ela.city}
      - BOSON_PRIVACY_MODE=${BOSON_PRIVACY_MODE:-false}
    volumes:
      - pc2-data:/app/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4200/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  pc2-data:
    driver: local
EOF
    echo -e "${GREEN}✓ Created docker-compose.yml${NC}"
}

# Pull and start the container
start_container() {
    echo ""
    echo "Pulling PC2 Node image..."
    docker pull "$PC2_IMAGE"
    
    echo ""
    echo "Starting PC2 Node..."
    cd "$INSTALL_DIR"
    docker compose up -d
    
    echo -e "${GREEN}✓ PC2 Node started!${NC}"
}

# Wait for node to be ready
wait_for_ready() {
    echo ""
    echo "Waiting for node to start..."
    
    for i in {1..30}; do
        if curl -s "http://localhost:${PC2_PORT}/api/health" > /dev/null 2>&1; then
            echo -e "${GREEN}✓ Node is ready!${NC}"
            return 0
        fi
        sleep 2
        echo -n "."
    done
    
    echo -e "${YELLOW}Node is still starting... check logs with: docker compose logs -f${NC}"
}

# Print success message
print_success() {
    PUBLIC_DOMAIN="${BOSON_PUBLIC_DOMAIN:-ela.city}"
    
    echo ""
    echo -e "${GREEN}════════════════════════════════════════════════════════════════${NC}"
    echo -e "${GREEN}                    Installation Complete!                       ${NC}"
    echo -e "${GREEN}════════════════════════════════════════════════════════════════${NC}"
    echo ""
    echo -e "Your PC2 Node is now running!"
    echo ""
    echo -e "  ${BLUE}Local URL:${NC}     http://localhost:${PC2_PORT}"
    echo -e "  ${BLUE}Public URL:${NC}    https://${PC2_USERNAME}.${PUBLIC_DOMAIN}"
    echo ""
    echo -e "Useful commands:"
    echo "  cd ${INSTALL_DIR}"
    echo "  docker compose logs -f    # View logs"
    echo "  docker compose restart    # Restart node"
    echo "  docker compose down       # Stop node"
    echo ""
    echo -e "${YELLOW}IMPORTANT: Open https://${PC2_USERNAME}.${PUBLIC_DOMAIN} to complete setup${NC}"
    echo ""
}

# Main installation flow
main() {
    check_docker
    get_username "$1"
    check_username_available
    create_install_dir
    create_compose_file
    start_container
    wait_for_ready
    print_success
}

# Run main
main "$@"
